In [3]:
import heapq
from sys import deactivate_stack_trampoline

from sympy.physics.units import frequency


In [4]:
pq = []


In [5]:
heapq.heappush(pq, (1, 3, 3, 5))
heapq.heappush(pq, (1, 2, 3, 5))
heapq.heappush(pq, (1, 2, 4, 5))
heapq.heappush(pq, (1, 3, 4, 5))
heapq.heappush(pq, (2, 3, 3, 5))
heapq.heappush(pq, (2, 3, 4, 5))

In [6]:
heapq.heappop(pq)

(1, 2, 3, 5)

In [7]:
import regex

In [8]:
pattern = " "

In [9]:
regex.findall(pattern, "21312 231354 231345")

[' ', ' ']

In [10]:
regex.split(pattern, "21312 231354 231345")

['21312', '231354', '231345']

In [11]:

for it in regex.finditer(pattern, "21312 2313d54 231345"):
    print(it.start(), it.end())
    print()

5 6

13 14



In [12]:
regex.split(r"(<\|end\|>)", "hello <|end|> world <|end|> bye")


['hello ', '<|end|>', ' world ', '<|end|>', ' bye']

In [13]:
chunk_bytes = "matched_chunk_str".encode("utf-8")
first = 0
first_bytes = bytes([chunk_bytes[first]])
second = 1
second_bytes = bytes([chunk_bytes[second]])

print(first_bytes, second_bytes, first_bytes + second_bytes, type(first_bytes), type(second_bytes))

b'm' b'a' b'ma' <class 'bytes'> <class 'bytes'>


In [14]:
def test_yield():
    for i in [[1, 2, 3, 3, 45], [324, 324542]]:
        for i_ele in i:
            yield i_ele


for i in test_yield():
    print(i)

1
2
3
3
45
324
324542


In [15]:
import torch
from einops import rearrange, einsum
from einops import rearrange, einsum


In [16]:
A = torch.randint(1, 100, (3, 3))
B = torch.randint(1, 100, (3, 3))
A

tensor([[42, 34, 53],
        [91, 58, 70],
        [31, 87, 68]])

In [17]:

C = torch.einsum("ij->ji", A)
print(A, C, A.T)

torch.equal(C, A.T)

tensor([[42, 34, 53],
        [91, 58, 70],
        [31, 87, 68]]) tensor([[42, 91, 31],
        [34, 58, 87],
        [53, 70, 68]]) tensor([[42, 91, 31],
        [34, 58, 87],
        [53, 70, 68]])


True

In [18]:
d_model = 64
d_ff = int(int((8 / 3) * d_model) / 64) * 64
d_ff

128

In [19]:
D = 16
pair_indices = torch.arange(
        0,
        16,
        2,
        dtype=torch.float32,
    )
pair_indices

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [20]:

power = (-pair_indices / D)
power

tensor([-0.0000, -0.1250, -0.2500, -0.3750, -0.5000, -0.6250, -0.7500, -0.8750])

In [21]:
frequencies = 10000 ** power
frequencies

tensor([1.0000e+00, 3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02, 3.1623e-03,
        1.0000e-03, 3.1623e-04])

In [22]:
positions = torch.arange(8)
positions

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
angles = positions[:,None] * frequencies[None,:]
angles.shape

torch.Size([8, 8])

In [24]:
x = torch.rand(4,8,16)
x_shape = x.shape


In [25]:
pairs = x.reshape(4,8,8,2)
x.

SyntaxError: invalid syntax (3615551903.py, line 2)

In [ ]:
pairs

In [ ]:
a = pairs[...,0]
b = pairs[...,1]
cos = angles.cos()
sin = angles.sin()

In [ ]:
rotated_a = a * cos - b * sin

In [ ]:
rotated_b = a * sin + b * cos

In [ ]:
torch.stack([rotated_a,rotated_b],dim=-1).shape

In [ ]:
(~(torch.tril(torch.randn(4,4) ) == 0)).int()

In [ ]:
q = [torch.randn(10,10) for _ in range(8)]
k = [torch.randn(10,10) for _ in range(8)]
v = [torch.randn(10,10) for _ in range(8)]


In [ ]:
for q1,k1,v1 in zip(q,k,v):
    print(f"q1.shape={q1.shape}, k1.shape={k1.shape}, v1.shape={v1.shape}")

In [ ]:
x1 = torch.tensor([[1,2],[3,4]])
x2 = torch.tensor([[5,6],[7,8]])
x1,x2

In [ ]:
x3 = torch.cat([x1,x2])

In [ ]:
y1 = torch.randint(1,10,(2,2))

In [27]:
x = torch.tensor([[1., 2., 3., 4.]])   # (1, 4)
x.reshape(-1,x.shape[-1]//2,2)

tensor([[[1., 2.],
         [3., 4.]]])

In [33]:
import torch.nn as nn

x = torch.randn(3,3)
silu = nn.SiLU()

In [29]:
torch.allclose(silu(x),torch.sigmoid(x) * x )


In [40]:
x = torch.randn(1,2,3,4)
x.shape[-2:]

torch.Size([3, 4])

In [51]:
target = torch.tensor([0,1,2,3,4])

In [52]:
source = torch.tensor([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
source.shape

torch.Size([6, 5])

torch.Size([5])

In [59]:
torch.log(torch.gather(source,-1,index=target.unsqueeze(-1)).squeeze(-1))

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094])

In [60]:
import math

In [61]:
math.log(0.3)

-1.2039728043259361

In [63]:
torch.stack([1,2,3,4,5,6,7,8])

TypeError: expected Tensor as element 0 in argument 0, but got list

In [68]:
x = torch.randn(4,4)

x

tensor([[ 0.4292,  0.6924, -0.9521, -0.5115],
        [ 0.2430,  2.1323, -0.8800, -0.2780],
        [ 0.6786, -2.3106, -1.8006,  1.1247],
        [ 0.1550,  0.6622,  0.4812,  1.4662]])

In [70]:
torch.roll(x,shifts=-1,dims=1)

tensor([[ 0.6924, -0.9521, -0.5115,  0.4292],
        [ 2.1323, -0.8800, -0.2780,  0.2430],
        [-2.3106, -1.8006,  1.1247,  0.6786],
        [ 0.6622,  0.4812,  1.4662,  0.1550]])